# Generated by Django 3.1.2 on 2020-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20201108_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='org_name',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(default='password', max_length=264),
        ),
    ]
