# Generated by Django 3.1.2 on 2020-11-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20201109_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
