# Generated by Django 3.1.2 on 2020-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20201120_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
